<form ng-submit="saveLicense()" class="form-horizontal">
	<sb-section title="'<?php echo addslashes(p__('Migastarter',"Your Module License Key")); ?>'" button="button">
		<div class="alert alert-info" ng-hide="!license.info_message">{{ license.info_message }}</div>
		<div class="alert alert-success" ng-hide="!license.success_message">{{ license.success_message }}</div>
		<div class="form-group">
			<div class="col-md-6">
				<label for="key"><?php echo addslashes(p__('Migastarter',"Your Module License Key")); ?></label>
				<input type="text" id="key" ng-model="license.key" class="form-control" placeholder="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" />
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-12">
				<button type="submit" class="btn btn-primary left"><?php echo p__('Migastarter',"Save"); ?></button>
				<sb-loader is_visible="form_loader_is_visible" type="'inner_content'" size="'small'" animation="'no'" class="form_loader"></sb-loader>
				<div class="clear"></div>
			</div>
		</div>
	</sb-section>
</form>

<form ng-submit="saveHelp()" class="form-horizontal">
	<sb-section title="'<?php echo addslashes(p__('Migastarter',"Your Module Help URL")); ?>'" button="button">
		<div class="alert alert-info" ng-hide="!help.info_message">{{ help.info_message }}</div>
		<div class="alert alert-success" ng-hide="!help.success_message">{{ help.success_message }}</div>
		<div class="form-group">
			<div class="col-md-6">
				<label for="key"><?php echo addslashes(p__('Migastarter',"Your Module Help URL")); ?></label>
				<input type="text" id="help_url" ng-model="help.help_url" class="form-control" placeholder="http:// or https://" />
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-12">
				<button type="submit" class="btn btn-primary left"><?php echo p__('Migastarter',"Save"); ?></button>
				<sb-loader is_visible="form_loader_help_is_visible" type="'inner_content'" size="'small'" animation="'no'" class="form_loader"></sb-loader>
				<div class="clear"></div>
			</div>
		</div>
	</sb-section>
</form>

<sb-section ng-show="app_licenses.length" title="'<?php echo __title("App Licenses"); ?>'" button="button">
	<table class="table">
		<thead>
			<tr>
				<th><strong><?php echo p__('Migastarter','App Id'); ?></strong></th>
				<th><strong><?php echo p__('Migastarter','App Name'); ?></strong></th>
				<th><strong><?php echo p__('Migastarter','Activated'); ?></strong></th>
				<th><strong><?php echo p__('Migastarter','Expiry'); ?></strong></th>
				<th><strong><?php echo p__('Migastarter','Status'); ?></strong></th>
			</tr>
		</thead>
		<tbody>
			<tr class="white-line" ng-repeat="app_license in app_licenses">
				<td>{{ app_license.app_id }}</td>
				<td>{{ app_license.app_name }}</td>
				<td>{{ app_license.activated }}</td>
				<td>{{ app_license.expiry }}</td>
				<td><span class="label label-sm" ng-class="{'label-success': app_license.status == 'Active', 'label-info': app_license.status == 'Expired'}"> {{ app_license.status }} </span></td>
			</tr>
		</tbody>
	</table>
</sb-section>