<?php
    $application = $this->getApplication();

    //app id property from application object

    $app_id = $application->getId();

    //complete option/feature object

    // $categories = new Migakitchen_Model_Category();
    $option = $this->getOptionValue();

    //value id property option value object

    $value_id = $option->getId();

    $application = $this->getApplication();
    //app id property from application object
    $app_id = $application->getId();
    //complete option/feature object
    $option = $this->getOptionValue();

    //value id property option value object
    $value_id = $option->getId();
    $setting  = new Migastarter_Model_Setting();
    $setting->find(1);
    // $license = Siberian_Json::decode(file_get_contents($this->getUrl('migastarter/public_license/validateapplicense?app_id=' . $app_id)));
    // licenses settings start
    $main_domain = __get('main_domain');
    if (! preg_match("~^(?:f|ht)tps?://~i", $main_domain)) {
        // If not exist then add http
        $main_domain = "https://" . $main_domain;
    }
    $curlSession = curl_init();
    curl_setopt($curlSession, CURLOPT_URL, $main_domain . '/migastarter/public_license/validateapplicense?app_id=' . $app_id);
    curl_setopt($curlSession, CURLOPT_BINARYTRANSFER, true);
    curl_setopt($curlSession, CURLOPT_RETURNTRANSFER, true);
    $jsonDataString = curl_exec($curlSession);
    curl_close($curlSession);
    $license = Siberian_Json::decode($jsonDataString);
    // licenses settings end

?>
<?php if ($license['success_message']): ?>
<?php if (! $license['is_platform']): ?>
<div class="alert alert-success"><?php echo $license['success_message']; ?></div>
<?php endif; ?>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
<p>
    <a href="<?php echo ! empty($setting->getHelpUrl()) ? $setting->getHelpUrl() : 'https://www.migastone.com/migalicense'; ?>"
        target="_blank" class="link-help color-blue btn">
        <i class="fa fa-question-circle"></i>
    </a>
</p>
<div id="migastarter" class="module-migastarter">

    <div class="navbar-btn btn-sm"></div>
    <!-- $settings->getRecipientEmail() display alret danger if empty/not set -->
    <?php if (empty($settings->getRecipientEmail())): ?>
    <div class="alert alert-danger">
        <?php echo p__('Migastarter', 'Please set the recipient email in the settings to receive notifications.'); ?>
    </div>
    <?php endif; ?>
    <ul class="nav nav-tabs custome_nav" role="tablist">
        <!-- category tab  -->
        <li role="presentation" class="active">
            <a href="#tab_category" aria-controls="tab_category" role="tab"
                data-toggle="tab"><?php echo p__('Migastarter', 'Category'); ?>
            </a>
        </li>
        <!-- Locations tab  -->
        <li role="presentation">
            <a href="#tab_locations" aria-controls="tab_locations" role="tab"
                data-toggle="tab"><?php echo p__('Migastarter', 'Locations'); ?></a>
        </li>
        <!-- Adverts tab  -->
        <li role="presentation">
            <a href="#tab_adverts" aria-controls="tab_adverts" role="tab" id="tab_adverts_link"
                data-toggle="tab"><?php echo p__('Migastarter', 'Adverts'); ?></a>
        </li>
        <li role="presentation">

            <a href="#tab_requests" aria-controls="tab_requests" role="tab"
                data-toggle="tab"><?php echo p__('Migastarter', 'Requests'); ?></a>

        </li>
        <li role="presentation">

            <a href="#tab_settings" aria-controls="tab_settings" role="tab"
                data-toggle="tab"><?php echo p__('Migastarter', 'Settings'); ?></a>

        </li>
        <li role="presentation">

            <a href="#tab_background" aria-controls="tab_background" role="tab"
                data-toggle="tab"><?php echo p__('Migastarter', 'Background'); ?></a>

        </li>

    </ul>

    <div class="tab-content">

        <!-- Categories start -->
        <div role="tabpanel" class="tab-pane active" id="tab_category">
            <h3 class="title-editor no-border-radius title-feature-indent border-blue">
                <?php echo p__("Migastarter", 'Import Adverts CSV'); ?>
            </h3>

            <div class="container-fluid subcontent content-feature">

                <div class="row">
                    <div class="col-md-6">
                        <form method="POST" action="<?php echo $this->getUrl('migastarter/application/importcsv') ?>" id="importcsv_form" enctype="multipart/form-data">
                            <div class="form-horizontal">
                                <div class="form-group">
                                    <div class="col-md-6">
                                        <label for="select-input">
                                            <?php echo p__("Migastarter", 'Select CSV to import') ?>:
                                        </label>
                                    </div>
                                    <div class="col-md-6">
                                        <input type="hidden" name="value_id" value="<?php echo $value_id ?>">
                                        <input type="hidden" name="app_id" value="<?php echo $app_id ?>">
                                        <input type="file" id="adverts_csv" name="adverts_csv" accept=".csv" required>
                                    </div>
                                    <div class="col-md-12">
                                        <button class="button btn btn color-blue" type="submit" id="import_csv_button">
                                            <?php echo p__("Migastarter", 'Import CSV'); ?>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    
                </div>
            </div>
            
        </div>
        <!-- Categories end -->
        
       

        <div role="tabpanel" class="tab-pane" id="tab_background">

            <?php echo $this->importBackground($option); ?>

        </div>
    </div>



</div>


<!-- added the styles and scripts for the new datatable. -->
<link rel="stylesheet" href="<?php echo $this->getUrl("/app/local/modules") . '/Migastarter/resources/design/desktop/flat/DataTables/'; ?>datatables.min.css">

<script src="<?php echo $this->getUrl("/app/local/modules") . '/Migastarter/resources/design/desktop/flat/DataTables/'; ?>datatables.min.js"></script>

<script>
// Form submissions
$("#migastarter_categories,#migastarter_locations,#migastarter_adverts,#migasdverts_settings1,#clearadverts_form").unbind('submit').submit(function () {
    reload(this, this.action, true, function (data) {
      console.log(data);
      page.reload();
    });
    return false;
});

</script>

<style type="text/css" media="screen">
table caption {
    padding: .5em 0;
}

table.dataTable th,
table.dataTable td {
    white-space: nowrap;
}





.margin-bkg {

    margin-top: 0px;

}



.pt30 {

    padding-top: 30px;

}



.heading {

    font-size: 20px;

    border-bottom: 1px solid #ccc;

    padding-bottom: 5px;

}



.pt30 {

    padding-top: 30px;

}



.mb10 {

    margin-bottom: 10px;

}



.mt30 {

    margin-top: 30px;

}



.mt60 {

    margin-top: 60px;

}



.margin-bkg {

    margin-top: 0px;

}



table {

    background-color: white;

}



table.dataTable {

    margin: 20px 0 10px;

    width: 100% !important;

}



table.dataTable th {

    text-align: left;

}



table.dataTable tbody tr.edit_product {

    cursor: pointer;

}



.dataTables_info {

    float: left;

    padding: 10px;

}



.dataTables_paginate {

    float: right;

}



.dataTables_paginate a {

    display: block;

    float: left;

    margin-left: 4px;

    padding: 6px;

}



.dataTables_paginate a.paginate_button_disabled {

    opacity: 0.3
}



.dataTable tbody tr:last-of-type {

    border-bottom: 0;

}



#table_appowners_filter input[type=search],

#table_table_products_filter input[type=search],

#table_usergroups_filter input[type=search],

#table_push_filter input[type=search],

#table_gallery_filter input[type=search],

#table_news_filter input[type=search],

#table_event_filter input[type=search],

#table_discount_filter input[type=search] {

    border-style: none none solid;

    border-style: none none solid;

    border-width: medium medium 2px;

    padding: 6px 12px;

    border-color: #b2b1b1;

    background-color: #f3f3f3;

    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);

    box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);

    -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;

    -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;

    transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;

}
</style>







<script>
//Background

bindForms('#tab_background');

$('#tab_background button#toggle_design').remove();

$('#tab_background #change_background_image').show();
</script>

<style>
.cancel {

    display: none;

}



.heading {

    font-size: 20px;

    border-bottom: 1px solid #ccc;

    padding-bottom: 5px;

}



.pt30 {

    padding-top: 30px;

}



.mb10 {

    margin-bottom: 10px;

}



.mt30 {

    margin-top: 30px;

}



.margin-bkg {

    margin-top: 0px;

}
</style>

<?php else: ?>
<?php if (! $license['is_platform']): ?>
<div class="alert alert-info"><?php echo $license['info_message']; ?></div>
<?php endif; ?>
<div id="migalicense" class="module-migalicense">
    <div class="navbar-btn btn-sm"></div>
    <ul class="nav nav-tabs custome_nav" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab_license" aria-controls="tab_license" role="tab"
                data-toggle="tab"><?php echo p__('Migastarter', 'License'); ?></a>
        </li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="tab_license">
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo p__('Migastarter', 'License'); ?>
            </h3>
            <div class="container-fluid content-feature pt30">
                <form id="appLicenseForm"
                    action="<?php echo $this->getUrl('migastarter/public_license/saveapplicense'); ?>">
                    <input type="hidden" name="value_id" value="<?php echo $option->getId(); ?>" />
                    <input type="hidden" name="app_id" value="<?php echo $app_id; ?>" />
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="col-sm-6">
                                <label for="key"><?php echo p__("Migastarter", "Your Module License Key") ?></label>
                                <input type="text" id="key" name="key" class="input-flat"
                                    placeholder="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <button class="button btn bt_save btn color-blue" type="submit">
                                    <?php echo p__('Migastarter', 'Save'); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    page.setCallback('didappear', function() {
        $('#appLicenseForm').submit(function() {
            reload(this, this.action, true, function(data) {
                page.reload();
            });
            return false;
        });
    });
    page.setCallback('willdisappear', function() {
        $('#appLicenseForm').unbind('submit');
    });
});
</script>
<style type="text/css" media="screen">
.pt30 {
    padding-top: 30px;
}
</style>
<?php endif; ?>